Update build-v8-win64.yml

diff --git a/.github/workflows/build-v8-win64.yml b/.github/workflows/build-v8-win64.yml
--- a/.github/workflows/build-v8-win64.yml
+++ b/.github/workflows/build-v8-win64.yml
@@ -42,38 +42,56 @@ jobs:
             run: |
                 set DEPOT_TOOLS_WIN_TOOLCHAIN=0
                 cd v8\v8
-                gn gen out/x64.debug --args='v8_target_cpu="x64" target_cpu="x64" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true default_crt="dynamic_crt" v8_enable_pointer_compression=true v8_monolithic=true v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                gn gen out/x64.debug --args='v8_target_cpu=\"x64\" target_cpu=\"x64\" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                ninja -C out/x64.debug v8_monolith v8_hello_world
 
           - name: Build V8 Windows x64 Release
             shell: cmd
             run: |
                 set DEPOT_TOOLS_WIN_TOOLCHAIN=0
                 cd v8\v8
-                gn gen out/x64.release --args='v8_target_cpu="x64" target_cpu="x64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true default_crt="dynamic_crt" v8_enable_pointer_compression=true v8_monolithic=true v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
+                gn gen out/x64.release --args='v8_target_cpu=\"x64\" target_cpu=\"x64\" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=\"\"'
+                ninja -C out/x64.release v8_monolith v8_hello_world
 
           - name: Build V8 Windows arm64 Debug
             shell: cmd
             run: |
                 set DEPOT_TOOLS_WIN_TOOLCHAIN=0
                 cd v8\v8
-                gn gen out/arm64.debug --args='v8_target_cpu="arm64" target_cpu="arm64" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true default_crt="dynamic_crt" v8_enable_pointer_compression=true v8_monolithic=true v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                gn gen out/arm64.debug --args='v8_target_cpu=\"arm64\" target_cpu=\"arm64\" is_debug=true symbol_level=2 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=true v8_enable_verify_heap=true v8_enable_object_print=true'
+                ninja -C out/arm64.debug v8_monolith v8_hello_world
 
           - name: Build V8 Windows arm64 Release
             shell: cmd
             run: |
                 set DEPOT_TOOLS_WIN_TOOLCHAIN=0
                 cd v8\v8
-                gn gen out/arm64.release --args='v8_target_cpu="arm64" target_cpu="arm64" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true default_crt="dynamic_crt" v8_enable_pointer_compression=true v8_monolithic=true v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=""'
+                gn gen out/arm64.release --args='v8_target_cpu=\"arm64\" target_cpu=\"arm64\" is_debug=false symbol_level=0 is_component_build=false v8_static_library=true v8_enable_pointer_compression=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_sandbox=true v8_enable_webassembly=true treat_warnings_as_errors=false enable_iterator_debugging=false v8_enable_verify_heap="" v8_enable_object_print=\"\"'
+                ninja -C out/arm64.release v8_monolith v8_hello_world
 
-          - name: Archive V8
+          - name: Test Product
             shell: pwsh
-            run: .\native\archive.bat "v8_windows_x64"
+            run: |
+                $ErrorActionPreference = "Stop"
+                $output1 = .\v8\v8\out\x64.debug\v8_hello_world.exe
+                if($output1 -like "Hello, World!*"){}else{
+                    Write-Error "Test failure: output is $output1"
+                    exit 1
+                }
+                $output2 = .\v8\v8\out\x64.release\v8_hello_world.exe
+                if($output2 -like "Hello, World!*"){}else{
+                    Write-Error "Test failure: output is $output2"
+                    exit 1
+                }
+
+          - name: Compress Product
+            shell: pwsh
+            run: |
+                $env:ProgramFiles\7-Zip\7z.exe .\v8\v8\out\x64.debug\
         
-          - name: Upload Archive
+          - name: Upload Archive Windows x64 Debug
             uses: actions/upload-artifact@v4
             with:
-                name: v8_windows_x64
-                path: |
-                    *.tar.xz
-                    *.7z
+                name: v8_windows_x64_debug
+                path: .\v8\v8\out\x64.debug\v8.7z
                 retention-days: 7
